site_name: RingCentral API Changelog
site_url: https://github.com/ringcentral/ringcentral-api-changelog.git
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-changelog.git
docs_dir: docs
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [fonts.js]
pages:
- Preface: 'index.md'
- 'v.1.0.33 (Dec 2017)': '1_0_33.md'
- 'v.1.0.32 (Oct 2017)': '1_0_32.md'
- 'v.1.0.31 (Jul 2017)': '1_0_31.md'
- 'v.1.0.30 (Apr 2017)': '1_0_30.md'
- 'v.1.0.29 (Feb 2017)': '1_0_29.md'
- 'v.1.0.28 (Dec 2016)': '1_0_28.md'

