site_name: RingCentral API Changelog
site_url: https://github.com/ringcentral/ringcentral-api-changelog.git
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/ringcentral-api-changelog.git
docs_dir: docs
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [fonts.js]
pages:
- Preface: 'index.md'
- 'v.1.0.28': '1_0_28.md'